### ISSUE TITLE
Add Difficulty Levels

### ISSUE THREAD

**Issue by aref-asadi** [aref-asadi/number_guessing_game#1]
#### Description
Add selectable difficulty levels to enhance gameplay variety and increase challenge. Each level should offer different number ranges and attempt limits, making the game more engaging for users of different skill levels.

#### Proposed Difficulty Levels:
- **Easy**: Guess numbers between 1 and 50 with a high attempt limit.
- **Medium**: Guess numbers between 1 and 100 with a moderate attempt limit.
- **Hard**: Guess numbers between 1 and 200 with a low attempt limit and fewer hints.

#### Benefits
- Adds replay value by allowing users to choose their preferred challenge level.
- Makes the game accessible for beginners while offering more difficult options for experienced players.
  
#### Additional Notes
Consider adding a dropdown menu or buttons in the GUI to let users select the difficulty before starting the game.

**Comment by BDadmehr0** [comment]
Assignee me

**Comment by aref-asadi** [comment]
perfect @BDadmehr0

**Comment by BDadmehr0** [comment]
https://github.com/aref-asadi/number_guessing_game/pull/6

**Comment by BDadmehr0** [comment]
close? @aref-asadi

**Comment by aref-asadi** [comment]
Yes dear @BDadmehr0 . This is done by @BDadmehr0 .
