### ISSUE TITLE
Add Timer to Game

### ISSUE THREAD

**Issue by aref-asadi** [aref-asadi/number_guessing_game#2]
#### Description
Implement a timer to create a time-based challenge, requiring players to guess the correct number within a limited time. This feature will add excitement and urgency to the gameplay, especially on higher difficulty levels.

#### Proposed Functionality:
- Display a countdown timer in the game window that starts when the game begins.
- Allow users to set or select a time limit (e.g., 30 seconds, 60 seconds) based on difficulty level.
- If the timer reaches zero, display a message indicating that the time has run out and provide an option to restart the game.

#### Benefits
- Adds an extra layer of challenge and engagement, encouraging quicker guesses.
- Makes the game suitable for time-based competitions or quick-play sessions.

#### Additional Notes
Consider providing a visual cue (e.g., color change) as time runs low to alert the player.

**Comment by BDadmehr0** [comment]
Assignee me

**Comment by aref-asadi** [comment]
perfect @BDadmehr0

**Comment by BDadmehr0** [comment]
https://github.com/aref-asadi/number_guessing_game/pull/6

**Comment by BDadmehr0** [comment]
close? @aref-asadi

**Comment by aref-asadi** [comment]
Yes. This is done by @BDadmehr0 . Thank you.
