### ISSUE TITLE
Add High Score and Record Tracking

### ISSUE THREAD

**Issue by aref-asadi** [aref-asadi/number_guessing_game#4]
#### Description
Implement a system to save and display high scores, such as the fewest number of attempts and fastest completion time. This feature will motivate players to improve their performance and offer a way to track personal bests.

#### Proposed Functionality:
- Record the player’s best performance (e.g., minimum attempts, fastest time) at each difficulty level.
- Display the high scores in a dedicated section of the game window or on a separate screen.
- Save records locally so they persist across sessions.

#### Benefits
- Adds a goal-oriented aspect to the game, encouraging replayability.
- Allows players to track their progress and set new personal records.

#### Additional Notes
Consider using a simple file (e.g., JSON) for local storage or a lightweight database if planning to expand the functionality in the future.

**Comment by bastienlogeot** [comment]
i can do that! :))

**Comment by TheMrQ** [comment]
I added the highscore !

**Comment by aref-asadi** [comment]
Thanks @bastienlogeot .
Thanks @TheMrQ .
This is done by @TheMrQ . Nice job.
