### ISSUE TITLE
Add Multiplayer Mode

### ISSUE THREAD

**Issue by aref-asadi** [aref-asadi/number_guessing_game#5]
#### Description
Implement a multiplayer mode where two players can compete by taking turns to guess the number. This feature will add a social, competitive element to the game, making it more engaging for multiple players.

#### Proposed Functionality:
- Allow players to enter their names at the start of the game and alternate turns.
- Track each player's attempts and display the winner when one of them guesses the correct number.
- Provide an option to restart the game for another round between players.

#### Benefits
- Adds a competitive layer, encouraging users to play with friends or family.
- Makes the game more interactive by allowing direct comparison between players.

#### Additional Notes
Consider displaying each player's current attempt count and score to make tracking progress easier.

**Comment by Tamar-Radin** [comment]
@aref-asadi can you assigne me?

**Comment by aref-asadi** [comment]
perfect. good luck @Tamar-Radin

**Comment by aref-asadi** [comment]
This is done by @Tamar-Radin
